SKILLS = [
    "python",
    "java",
    "c++",
    "sql",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "nlp",
    "data analysis",
    "pandas",
    "numpy",
    "flask",
    "fastapi",
    "aws",
    "docker",
    "git",
    "github",
    "tableau",
    "power bi",
    "scikit-learn",
    "computer vision",
    "api",
    "linux",
    "html",
    "css",
    "javascript"
]